### ISSUE TITLE
Clarify use of mask transparency

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/Thumby-Website#13]
From:
https://thumby.us/API/Blit-Draw/

Where `maskBitmapData` states:
> each bit being 1 (transparent) or 0 (not-drawn)

and `maskSprite` states:
> (pixels set to 1 are transparent, while 0 pixels are not drawn)

This is confusing! Transparent and 'not drawn' sound equivalent... Perhaps 'Opaque' should be used as the opposite to 'Transparent'? ...But does the mask's bits also interact with the Key value set?...

For reference ~
Wiki doc: [here](https://en.wikipedia.org/wiki/Mask_(computing)#Image_masks).
Other lib doc: [here](https://mlxxxp.github.io/documents/Arduino/libraries/Arduboy2/Doxygen/html/classSprites.html#a6f52e84e29b6180797a5ab53ccab948d).

**Comment by Lennevia** [comment]
We found a little oopsie in the library as I started looking into this issue. Fixing it someday in the future, issue here: https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/issues/90
The documentation will probably change a little once that is fixed.

For now, I added some examples to clarify how the masking works in application: https://github.com/TinyCircuits/Thumby-Website/commit/32961f39f19ca2eb0b7333661380e1ffa79cb473

I haven't updated the documentation because I'm not sure opaque fits within this context. The masked bitmap outlines what should be 'cut away' from the original bitmap using the key value to reference the 0/1 black/white corresponding pixel color for what should be 'cut away' and the rest is not drawn, or rather 'not cut away'. So the transparency mask is different from the not drawn pixels leftover from the transparency mask. There isn't an opaque component to the mask bitmap, just the `bitmapData` bitmap is 'seen'. This is confusing nomenclature at its core, so I hope the example helps. If you want to suggest a change in a PR, I'd be happy to look it over! 

I'll leave this issue open for now in case you have any more comments on it!

**Comment by Lennevia** [comment]
We're leaving the `key` argument since removal and an API update to fix it would be a breaking change that would affect many of the games that currently exist. It's now just a fun little legacy goof: https://github.com/TinyCircuits/Thumby-Website/commit/93696bd92c785b1da781feae87ddea19b173d68b

**Comment by ace-dent** [comment]
Hi,
The extra details look good... but you haven't really addressed the language issue here:

> white pixels that are not drawn

and

> 0 pixels are not drawn

I think you just need to replace "not drawn" with "opaque"?
